name: camelus
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.10.1+93

environment:
  sdk: ">=3.9.2 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  material_ui: any
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.21.2
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  flutter_riverpod: ^3.0.3
  http: ^1.2.1
  flutter_svg: ^2.0.7
  timeago_flutter: ^3.5.0
  badges: ^3.1.2
  uuid: ^4.4.2
  cached_network_image: ^3.3.1
  bip340: ^0.3.1
  bech32: ^0.2.1
  hex: ^0.2.0
  flutter_secure_storage: ^10.0.0
  crypto: ^3.0.2
  url_launcher: ^6.1.7
  lottie: ^3.0.0
  flutter_launcher_icons: ^0.14.1
  file_picker: ^12.2.0
  image_picker: ^1.2.3
  mime: ^2.0.0
  photo_view: ^0.15.0
  qr_flutter: ^4.0.0
  shared_preferences: ^2.5.5

  custom_refresh_indicator: ^4.0.1
  flutter_cache_manager: ^3.4.1
  web_socket_channel: ^3.0.1
  http_parser: ^4.0.2
  path_provider: ^2.1.4
  pointycastle: ^4.0.0
  #device_preview: ^1.1.0
  bip39_mnemonic: ^4.0.1
  #bip32: ^2.0.0
  bip32_keys: ^3.1.4

  crop_your_image: ^2.0.0
  package_info_plus: ^10.2.1
  rxdart: ^0.28.0
  shimmer: ^3.0.0
  flutter_force_directed_graph: ^1.0.7
  objectbox: ^5.3.2
  objectbox_flutter_libs: any
  sembast: ^3.8.9+1
  sembast_web: ^2.4.5+1
  intl: any
  app_links: ^7.0.0
  #phosphor_flutter: ^2.1.0
  phosphoricons_flutter: ^1.0.0

  # ndk imports
  ndk: ^0.9.0
  ndk_flutter: ^0.9.0
  #nip07_event_signer: ^1.0.10-dev.5
  #ndk_rust_verifier: ^0.5.0

  ndk_objectbox: ^0.2.12+1
  
  
  image: ^4.3.0
  flutter_list_view: ^1.1.29
  xxh3: ^1.2.0
  serverpod_flutter: 3.3.1
  apipod_client:
    path: ./apipod/apipod_client
  firebase_messaging: ^16.2.0
  firebase_core: 4.7.0
  flutter_local_notifications: ^19.4.2
  path: ^1.9.1
  share_plus: ^13.3.0
  connectivity_plus: ^6.1.4
  flutter_link_previewer: ^3.2.2
  flutter_chat_types: ^3.6.2
  visibility_detector: ^0.4.0+2
  pretty_qr_code: ^3.5.0
  mobile_scanner: ^7.4.0
  bolt11_decoder: ^1.0.2
  decimal: ^2.3.3
  video_player: ^2.13.0
  window_manager: ^0.5.1
  go_router: ^17.1.0
  timeago: ^3.7.1
  flutter_localizations:
    sdk: flutter
  system_theme: ^3.3.0
  ur:
    path: ../ndk/packages/bc_ur
  mapbox_maps_flutter: ^2.30.0
  geolocator: ^14.0.2
  flutter_tts: ^4.2.5
  dart_geohash: ^2.1.0

  

  



dependency_overrides:
  ur:
     git:
       url: https://github.com/relaystr/ndk.git
       path: packages/bc_ur
       #ref: tmp/camelus/1-10-0

  # ndk:
  #   path: ../ndk/packages/ndk
  #   #  git:
  #   #    url: https://github.com/relaystr/ndk.git
  #   #    path: packages/ndk
  #   #    ref: tmp/camelus/1-10-0
    
  # ndk_flutter:
  #   path: ../ndk/packages/ndk_flutter
    #  git:
    #    url: https://github.com/relaystr/ndk.git
    #    path: packages/ndk_flutter
    #    ref: tmp/camelus/1-10-0
  # nip07_event_signer:
  #   path: ../ndk/packages/nip07_event_signer
    #  git:
    #    url: https://github.com/relaystr/ndk.git
    #    path: packages/nip07_event_signer
    #    ref: tmp/camelus/1-10-0
  #ndk_rust_verifier:
  #  path: ../ndk/packages/rust_verifier
    #git:
    #  url: https://github.com/relaystr/ndk.git
    #  path: packages/rust_verifier
  # ndk_objectbox:
  #   path: ../ndk/packages/objectbox
    # git:
    #    url: https://github.com/relaystr/ndk.git
    #    path: packages/objectbox
    #    ref: tmp/camelus/1-10-0

  #ndk_amber:
    #path: ../ndk/packages/amber
    #git:
     # url: https://github.com/relaystr/ndk.git
      #path: packages/amber
    #  ref: nip-59-gift-wrap

  # bip32:
  #   git: 
  #     url: https://github.com/5eeman/bip32-dart.git
  #     ref: 9db7cf7c9e3a4e61f145ca43b01469c6464dce89



dev_dependencies:
  build_runner: ^2.10.4 
  mockito: ^5.6.1
  flutter_test:
    sdk: flutter
  integration_test: 
    sdk: flutter

  flutter_lints: ^6.0.0
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3 
  #riverpod_generator: ^2.4.3
  test: ^1.25.7
  objectbox_generator: any
 

  
  #layerlens: ^1.0.17

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.

flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - assets/app_icons/
    - assets/animations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-Italic.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


### run generator:
# dart run build_runner build