# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end



  desc "Deploy a new version to the Google Play"
  lane :production do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Deploy a new version to open Testing Track"
  lane :beta do
    gradle(
      task: 'bundle',
      build_type: 'Release'
    )
    upload_to_play_store(
      track: 'beta',
      aab: '../build/app/outputs/bundle/release/app-release.aab'
      json_key_data: ENV['G_PLAY_FASTLANE_SERVICE_ACCOUNT']
    )
  end
end
