name: Flutter Android CI/CD

on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '20'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.4'  
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get



    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install Fastlane
      run: |
        cd android
        gem install bundler
        bundle install

    - name: Deploy to Test Track Play Store
      env:
        G_PLAY_FASTLANE_SERVICE_ACCOUNT: ${{ secrets.G_PLAY_FASTLANE_SERVICE_ACCOUNT }}
      run: |
        cd android
        bundle exec fastlane android beta